### ISSUE TITLE
Plugin Code box needs max-height

### ISSUE THREAD

**Issue by Miniland1333** [LibreTexts/ckeditor-binder-plugin#32]
When attempting to insert very long pieces of code, the code block expands beyond the viewport and thus makes the buttons at the bottom inaccessible. Scrolling doesn't work since it only scrolls the editor rather than the plugin. 

My recommendation for the CSS:
```CSS
.thebelab-cell {
    max-height: 50vh;
    overflow: auto;
}
```

Image of the issue:

![image](https://user-images.githubusercontent.com/12994749/73126703-b987f600-3f6a-11ea-9125-dcb6e979e921.png)
