### ISSUE TITLE
Remove trailing colon from labels

### ISSUE THREAD

**Issue by Miniland1333** [LibreTexts/ckeditor-binder-plugin#65]
In plugin.scss, please add a line of CSS to counteract this CSS:
```CSS
.mt-label:after, label:after {
    content: ':';
}
```

![image](https://user-images.githubusercontent.com/12994749/77362905-0855d000-6d0f-11ea-911d-fa9169305f7f.png)
